name: bayes_env
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - ipython=8.30.0
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - numpy=1.26.4
  - numpy-base=1.26.4
  - pandas=2.2.3
  - pip=24.2
  - python=3.12.8
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - tqdm=4.66.5
  - pip:
      - flax==0.10.5
      - imageio==2.37.0
      - jax==0.5.3
      - jaxlib==0.5.3
      - jinja2==3.1.6
      - optax==0.2.4
      - pytest==8.3.5
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - seaborn==0.13.2
      - ucimlrepo==0.0.7
      - nbconvert==7.16.6
      - rarfile
